# Generated by Django 5.0 on 2023-12-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=500)),
                ('g_map', models.TextField()),
            ],
        ),
    ]
