# Generated by Django 5.0 on 2024-01-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blog_feedback_feedbacksection_infosection_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosection',
            name='footer_text',
            field=models.TextField(default='lorem'),
            preserve_default=False,
        ),
    ]
