# Generated by Django 5.0 on 2024-01-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_contact_g_map_alter_about_bg_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
