# Generated by Django 5.0 on 2024-01-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blogssection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='blogssection',
            options={'verbose_name_plural': 'Blogs Section'},
        ),
    ]
