# Generated by Django 5.0 on 2024-01-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sending Date'),
        ),
    ]
